# Generated by Django 3.0.3 on 2020-02-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('subcriber_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'subscriber',
                'ordering': ['-created_date'],
            },
        ),
    ]
